---
  - name: Ensure Apache is installed or latest version
    apt:
      name: apache2
      state: latest
      update_cache: yes

  - name: Make sure Apache is running
    systemd:
      name: apache2
      state: started